name: "Post-Integration"

on:
  push:
    branches:
      - main
      - '!stable'
      - '!release'
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/**'

jobs:
  merge-to-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nelonoel/branch-name@v1.0.1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build and run unit tests
        run: |
          dotnet build -c Debug /p:UseSourceLink=true
          dotnet test -c Debug --no-build

      - name: Merge to stable
        run: |
          git checkout stable
          git merge --ff-only main

      - name: Creating library package for pre-release
        run: dotnet pack -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages -p:RepositoryBranch=$BRANCH_NAME -p:ContinuousIntegrationBuild=true

      - name: Creating library package for release
        run: dotnet pack -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages -p:RepositoryBranch=$BRANCH_NAME -p:ContinuousIntegrationBuild=true /p:PublicRelease=true
