name: "Post-Integration"

on:
  push:
    branches:
      - main
      - '!stable'
      - '!release'
    paths:
      - 'src/**'
      - 'test/**'
      - '!.github/**'
      - '.github/workflow/PostIntegration.yml'

jobs:
  merge-to-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nelonoel/branch-name@v1.0.1

      - uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build and run unit tests
        run: |
          dotnet build -c Debug /p:UseSourceLink=true
          dotnet test -c Debug --no-build

      - name: Merge to stable
        run: |
          git checkout stable
          git merge --ff-only main

      - name: Creating library package for pre-release
        run: dotnet pack -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages -p:RepositoryBranch=$BRANCH_NAME -p:ContinuousIntegrationBuild=true

      - name: Creating library package for release
        run: dotnet pack -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages -p:RepositoryBranch=$BRANCH_NAME -p:ContinuousIntegrationBuild=true /p:PublicRelease=true

      - name: Push packages to GitHub Package Registry
        run: dotnet nuget push ${GITHUB_WORKSPACE}/packages/'atc-coding-rules-updater.'${NBGV_SimpleVersion}'.nupkg' -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/atc-net/index.json --skip-duplicate
