name: "Post-Integration"

on:
  push:
    branches:
      - main
      - '!stable'
      - '!release'
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/**'

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Building library in release mode
        run: dotnet build -c Release -p:ContinuousIntegrationBuild=true

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Running unit tests
        run: |
          dotnet build -c Debug /p:UseSourceLink=true
          dotnet test -c Debug --no-build
